<?php

namespace AppBundle\Repository;

/**
 * Event_has_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Event_has_UserRepository extends \Doctrine\ORM\EntityRepository
{
}
